lab:
  Mono:
    black:
      max:
      - 89
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 220
      - 160
      - 115
      min:
      - 20
      - 70
      - 0
    green:
      max:
      - 255
      - 110
      - 255
      min:
      - 47
      - 0
      - 135
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 130
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
  Stereo:
    black:
      max:
      - 90
      - 255
      - 255
      min:
      - 0
      - 0
      - 0
    blue:
      max:
      - 220
      - 160
      - 110
      min:
      - 20
      - 120
      - 0
    green:
      max:
      - 255
      - 118
      - 255
      min:
      - 30
      - 0
      - 105
    red:
      max:
      - 255
      - 255
      - 255
      min:
      - 0
      - 150
      - 140
    white:
      max:
      - 255
      - 255
      - 255
      min:
      - 193
      - 0
      - 0
    yellow:
      max:
      - 255
      - 255
      - 255
      min:
      - 135
      - 129
      - 132
size:
  height:
  - 480
  width:
  - 640
